### ISSUE TITLE
merging with neovim

### ISSUE THREAD

**Issue by parisni** [ryvnf/readline.vim#5]
Hi

your package is great. It is discussed there to merge it in neovim https://github.com/neovim/neovim/issues/10799
you may be interested

**Comment by ryvnf** [comment]
Thanks for letting me know!

**Comment by parisni** [comment]
anyway: your package really rocks ! Command mode should apply the readline natively in vim. This is the result of ignorance of those universal shortcuts.

**Comment by ryvnf** [comment]
I'm flattered that you think that. :blush: I put it here in the hopes that other people would find it useful. This plugin haven't had much exposure so I was pleasantly surprised that you managed to find it. I am following the neovim issue, and hope it is merged. Even if it doesn't get merged I'm glad the plugin got some extra exposure.

Also, while I do agree that it would be cool to have Vim link to Readline for the command-line. There are reasons it does not. Partially because some commands like Ctrl-R would cause conflicts, and historical reasons. But Vim could definitely have put in more effort to make its command-line interface more similar to Readline.

**Comment by parisni** [comment]
BTW I added the support in nix packages recently (see https://github.com/NixOS/nixpkgs/pull/66829 ).

**Comment by ryvnf** [comment]
Since the issue on Neovim was closed and the discussion stopped this probably will not happen any time soon so I am closing this issue. Thanks again for your enthusiasm.
