### ISSUE TITLE
No `delete_longword()`

### ISSUE THREAD

**Issue by noscript** [ryvnf/readline.vim#7]
I miss a counterpart for `rubout_longword()` to delete forward to end of space delimited word :smile: 

P.S. It would be great to update the documentation using established Vim terms:
- a space delimited word (a.k.a long word) is _WORD_.
- a regular word that is delimited by `iskeyword` is _word_ (`:h word` vs `:h WORD`).

**Comment by ryvnf** [comment]
I haven't added a `delete_longword` because I don't think there is such a command in Readline or similar command-line interfaces. If you know a suitable key binding which exists in Readline or other shell interfaces I will consider adding it. I have chosen to avoid adding mappings which does not have a corresponding command in Bash or Readline. This is because I want the scope of the plugin to be focused Readline emulation in Vim's command-line.

Regarding the documentation. I've chosen not to use the Vim terms `WORD` and `word` to avoid confusion because the plugin handles the word boundaries slightly differently from Vim. You can compare `Alt-b` with `b` in command-line mode and you will see that there is a slight difference in behaviour between the commands. The word-mappings in the plugin are implemented to behave just like in Readline, which has a different behaviour compared to Vim.

**Comment by noscript** [comment]
Not sure about default keybinding, they tend to differ, but there are commands in zsh and bash (which uses readline).

In zsh there is [`backward-kill-word`](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html). Try binding it to <kbd>ctrl+k</kbd>:
```
zsh> bindkey '^k' backward-kill-word
```

Bash has [`shell-backward-kill-word`](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html) which works not exactly as wanted, since also deletes the leading space character. Anyways, example binding to <kbd>ctrl+k</kbd>:
```
bash> bind "\C-k":shell-backward-kill-word
```

If you want to keep it as close to readline origins as possible, no problem.

**Comment by ryvnf** [comment]
As it does not appear to be a standard keybinding for this. I don't think there is a way to implement it as a mapping which fits with the current scope of the plugin. One think I might consider in the future is to make it possible to bind line editing commands using `<plug>`. So one could write:

    cnoremap <c-k> <plug>backward-kill-word

To get what you want. Then the problem of finding a suitable mapping does not exist anymore. But I think that would be a separate issue. I generally want to avoid adding features unless I know multiple people want them, to keep the plugin small and simple.
